### ISSUE TITLE
We should make sure other listeners don't get triggered by keypresses when the _hold key_ is down.

### ISSUE THREAD

**Issue by carbon-steel** [jchang504/keeptabs#35] opened 2017-06-05 08:01 UTC
Some websites like google drive and gmail use keypresses as commands. We should make sure that keypresses from our hotkeys do not trigger these commands when the _holdkey_ is held down.

**Comment by jchang504** [comment] 2017-06-05 17:00
Have you found a case where this doesn't work? I'm pretty sure I've already implemented this correctly.

**Comment by carbon-steel** [comment] 2017-06-09 12:46
In Google Drive (when you're logged in), using <Esc> + f doesn't activate the hotkey, but opens a dropdown on the page instead. Also, <Esc> + / doesn't open a search tabs page but just makes the page focus on the search query at the top.

Similar things happen on Gmail (if you have your Gmail hotkeys activated in your settings).

**Comment by jchang504** [comment] 2017-06-10 02:28
I can't reproduce those two on https://drive.google.com/drive/my-drive and I've been using my keyboard shortcuts on Gmail fine. Are you sure you weren't working on pages that hadn't been refreshed since you reloaded KeepTabs for some reason? Were KeepTabs hotkeys working at all on those pages (even ones that don't overlap)? If not, you can open up the console and confirm that the pages haven't been refreshed since a KT reload if you see runtime errors talking about runtime.connect and stuff like that.

**Comment by jchang504** [comment] 2017-07-23 03:33
I just tested this on Mac Chrome with all 4 hold key options (context menu key doesn't exist on Mac) and KeepTabs works as expected on Gmail and Drive. The keyboard shortcuts for those sites don't activate when the hold key is pressed and they do when it's not. I think something else must have been going on when you observed this (e.g. what I mentioned above). Closing this until it can be reliably reproduced.

**Closed as completed by jchang504** 2017-07-23 03:33 UTC
Labels: WAI
